<section class="block b-form b-form-inline">
	<header class="head">
	<h1>Добавление дохода</h1>
	</header>
	<div class="body">

	<?php
	$form = $this->form;
	$form->setAttribute('action', '/categories/income/add');
	$form->prepare();
	echo $this->form()->openTag($form);
	?>
	<div class="group">
		<div class="form_element">
			<?=$this->formRow($form->get('date'))?>
		</div>
		<div class="form_element">
			<?=$this->formRow($form->get('amount'))?>
		</div>
		<div class="form_element">
			<?=$this->formRow($form->get('categories_id'))?>
		</div>
		<div class="form_element">
			<?=$this->formRow($form->get('account_id'))?>
		</div>
		<div class="form_element">
			<?=$this->formRow($form->get('comment'))?>
		</div>
		<div class="clear"></div>
	</div>
	<div class="form_element button">
		<?=$this->formRow($form->get('submit'))?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
	<div class="clear"></div>
	</div>
</section>