<?php echo $this->doctype(); ?>
<html lang="ru">
	<head>
		<meta charset="utf-8" />
		<title><?=$this->title?></title>
		<link rel="stylesheet" href="<?=$this->basePath()?>/css/__common.css" />
		<script src="<?=$this->basePath()?>/js/lib/jquery-2.1.3.min.js"></script>
		<script src="<?=$this->basePath()?>/js/lib/jquery-ui.min.js"></script>
		<script src="<?=$this->basePath()?>/js/lib/jquery.jcarousel.min.js"></script>
		<script src="<?=$this->basePath()?>/js/lib/dynamic-element.js"></script>
		
		<script src="<?=$this->basePath()?>/js/init.js"></script>
	</head>
	<body>
	
		<section id="wrapper">
			<section class="top_panel">	
				<?php echo $this->AuthHelper()->user(); ?>
				<nav>
					<?php 
						echo $this->navigation('Navigation')->menu()->setPartial('application/navigation/menu')->render();
						//echo $this->navigation('Navigation')->menu()->render();
					?>
				</nav>
			</section>
			<section class="main">
				<section class="view">
					<?= $this->content; ?>
				</section>
				
				<section class="clear"></section>
			</section>
			<section id="empty"></section>
			<footer>
				&copy; 2005 - <? echo date('Y'); ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
			</footer>
		</section>
		
		<?php echo $this->AuthHelper()->timeoutScript(); ?>
	</body>
</html>