<style>
	.b-login{
		width: 350px;
		margin: 0 auto;
		float:none;
		padding-bottom:10px;
	}
	
	a.refresh_captcha{
		display:block;
		clear:both;
		float:left;
		font-size:0.97em;
		text-decoration:none;
		border-bottom: 1px dashed #9299a2;
		color:#9299a2 !important;
	}
	
	a.refresh_captcha:active{
		color:#009ecf !important;
		border-bottom: 1px dashed #009ecf;
	}
</style>

<section class="block b-form b-login">
	<header class="head">
	<h1>Аутентификация</h1>
	</header>
	<div class="body">
	<?php if($message):?>
		<div class="message">
			<span class="<?=$is_success ? 'success' : 'error'?>"><?=$message;?></span>
		</div>
	<?php endif;?>
	
	<?php
	$form = $this->form;
	$form->prepare();
	echo $this->form()->openTag($form);
	foreach($form as $el):
	$name = $el->getName();
	?>	
		<div class="form_element <?=$name?>">
			<label>
				<span><?=$el->getLabel()?></span>
				<?=$this->formElement($el)?>
				<?php if($name=='captcha'):?><a class="refresh_captcha" href="#">Обновить картинку</a><?php endif; ?>
			</label>
			
		</div>
	<?php endforeach; ?>
	<div class="clear"></div>
	</div>
</section>

<script>
	function refresh_captcha(captcha_cont)
	{
		$.ajax({
			method:'post',
			url:'/auth/refresh_captcha',
			dataType:'json',
			success: function(res){
				captcha_cont.find('img').attr('src', res.captcha_src);
				captcha_cont.find("input[name='captcha[id]']").val(res.captcha_id);
			}
		});
	}
	
	$('.captcha img').click(function(){
		refresh_captcha($(this).closest('.captcha'));
	});
	
	$('.captcha a.refresh_captcha').click(function(){
		refresh_captcha($(this).closest('.captcha'));
		return false;
	});
</script>