<style>
	.b-login{
		width: 350px;
		height:250px;
		margin: 0 auto;
		float:none;
	}
</style>

<section class="block b-form b-login">
	<header class="head">
	<h1>Аутентификация</h1>
	</header>
	<div class="body">
	<?php if($message):?>
		<div class="message">
			<span class="<?=$is_success ? 'success' : 'error'?>"><?=$message;?></span>
		</div>
	<?php endif;?>
	
	<?php
	$form = $this->form;
	
//	$form->setAttribute('action', '/categories/income/add');
	$form->prepare();
	echo $this->form()->openTag($form);
	?>
	<div class="form_element">
		<?=$this->formRow($form->get('login'))?>
	</div>
	<div class="form_element">
		<?=$this->formRow($form->get('pwd'))?>
	</div>
	<div class="form_element button">
		<?=$this->formRow($form->get('submit'))?>
	</div>
	<?php echo $this->form()->closeTag(); ?>
	<div class="clear"></div>
	</div>
</section>